sudo: required
services:
  - docker

before_install:
  - docker build -t zerodump/docker-react -f Dockerfile.dev .

script:
  - docker run zerodump/docker-react npm run test -- --coverage
  #docker run -e CI=true zerodump/docker-react npm run test